### ISSUE TITLE
User Authentication (feature request)

### ISSUE THREAD

**Issue by Heikrana** [darshikaguptaa/Library#3]
Currently, the **books added** by a user are being **stored** in the **client's local storage**. If somehow the local storage is **deleted** (intentionally or otherwise) then the **books** will also get **lost**.

One way of solving this problem is by _creating a unique user ID and storing this ID alongside the books in a database on the server instead of the client_.
Initially, the client's request (get books) will be handled by the local storage, but if the local storage is empty, then the client can query the database server to get the books.

Thanks in advance.

**Comment by darshikaguptaa** [comment]
Thank you for adding this feature. I appreciate it !
